### ISSUE TITLE
Missing "detok_spacy.py"

### ISSUE THREAD

**Issue by leodotnet** [kanekomasahiro/bert-gec#1]
In generate.sh at line 12,   python -u detok_spacy.py $input $OUTPUT_DIR/test.bert.src
However, "detok_spacy.py" is missing in the folder.

Where to get "detok_spacy.py" ?
Thanks.

**Comment by kanekomasahiro** [comment]
Thank you for letting me know. I added "detok_spacy.py" and renamed it "detok.py".
