### ISSUE TITLE
How to reproduce the result?

### ISSUE THREAD

**Issue by HelenaHlz** [kanekomasahiro/bert-gec#10]
Hi, I exchange the training dataset to the BEA-2019 workshop official shared task dataset. But when I run the train.sh, it only runs 13 epochs rather than 30 epochs.

Is there any change in train.sh? or which checkpoint model did u use?

**Comment by kanekomasahiro** [comment]
My model was trained to a maximum of 19 epochs. 
If you need the trained model, you can download it from the README.

**Comment by HelenaHlz** [comment]
> My model was trained to a maximum of 19 epochs.
> If you need the trained model, you can download it from the README.

Thanks. 
If i just run ur train.sh for 19 epochs, could i get the model like u mentioned in the README?
Or u did some modification?
1. Did u only use the W&I-train training dataset without Lang-8, NUCLE, FCE-train to train this model? 
2. Did u set decoder-no-bert to just fuse bert on encoder?

I use the BEA-2019 workshop official shared task dataset and set decoder-no-bert, but the best checkpoint is the first checkpoint. It's really confused.

**Comment by HelenaHlz** [comment]
I'm trying other methods to fuse bert. So I want to know more about the training details. Hope to receive your reply.

**Comment by kanekomasahiro** [comment]
Since I chose the checkpoint_best.pt from those trained checkpoints, I can not guarantee you'll get the same results.
I used W&I-train, Lang-8, NUCLE and FCE-train for training data. I did not use decoder-no-bert. --bert-model-name in  train.sh sets BERT you want to use.
